/*
 * Harbour 3.2.1dev (r2609180937)
 * GNU C 16.2.1 (64-bit)
 * Generated C source from "/home/jack/Projects/hix/hix_server.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( GETHARUFONTDIR );
HB_FUNC_EXTERN( GETHARUFONTLIST );
HB_FUNC_EXTERN( HARUADDFONT );
HB_FUNC_EXTERN( HIXSHOULDABORT );
HB_FUNC_EXTERN( HIX_ACCESSLOG );
HB_FUNC_EXTERN( HIX_ACCESSLOGCLOSE );
HB_FUNC_EXTERN( HIX_ACCESSLOGINIT );
HB_FUNC_EXTERN( HIX_ADMINCHECK );
HB_FUNC_EXTERN( HIX_ADMINLOGINGET );
HB_FUNC_EXTERN( HIX_ADMINLOGINPOST );
HB_FUNC_EXTERN( HIX_ADMINLOGOUT );
HB_FUNC_EXTERN( HIX_ADMINSETUPGET );
HB_FUNC_EXTERN( HIX_ADMINSETUPPOST );
HB_FUNC_EXTERN( HIX_ANOMALYRECORD );
HB_FUNC_EXTERN( HIX_ANOMALYSTATS );
HB_FUNC_EXTERN( HIX_APPCONFIG );
HB_FUNC_EXTERN( HIX_APPROOT );
HB_FUNC_EXTERN( HIX_BLOCK );
HB_FUNC_EXTERN( HIX_BOOTLOG );
HB_FUNC_EXTERN( HIX_BOOTLOGACTION );
HB_FUNC_EXTERN( HIX_BOOTLOGADD );
HB_FUNC_EXTERN( HIX_BOOTLOGISVERBOSE );
HB_FUNC_EXTERN( HIX_BOOTLOGRESET );
HB_FUNC_EXTERN( HIX_BOOTLOGSECTION );
HB_FUNC_EXTERN( HIX_BOOTLOGSHOW );
HB_FUNC_EXTERN( HIX_BOOTLOGVERBOSE );
HB_FUNC_EXTERN( HIX_CLOSEDBFAREAS );
HB_FUNC_EXTERN( HIX_COMPILEFILE );
HB_FUNC_EXTERN( HIX_CONFIGAPP );
HB_FUNC_EXTERN( HIX_CONFIGAPPDEFAULTS );
HB_FUNC_EXTERN( HIX_CONFIGAPPLOAD );
HB_FUNC_EXTERN( HIX_CONFIGAPPMERGE );
HB_FUNC_EXTERN( HIX_CONFIGAPPRESET );
HB_FUNC_EXTERN( HIX_CONFIGAPPSAVE );
HB_FUNC_EXTERN( HIX_CONFIGAPPSET );
HB_FUNC_EXTERN( HIX_CONFIGMERGE );
HB_FUNC_EXTERN( HIX_CONSTANTEQ );
HB_FUNC_EXTERN( HIX_CSRFGENRANDOM );
HB_FUNC_EXTERN( HIX_CSRFMAKETOKEN );
HB_FUNC_EXTERN( HIX_CSRFVALIDTOKEN );
HB_FUNC_EXTERN( HIX_DATECOMPILE );
HB_FUNC_EXTERN( HIX_DBF );
HB_FUNC_EXTERN( HIX_DBG );
HB_FUNC_EXTERN( HIX_DBGERROR );
HB_FUNC_EXTERN( HIX_DBGRESET );
HB_FUNC_EXTERN( HIX_DBGSETFILE );
HB_FUNC_EXTERN( HIX_DETECTPROTOCOL );
HB_FUNC_EXTERN( HIX_DOERRORVIEW );
HB_FUNC_EXTERN( HIX_ECHO );
HB_FUNC_EXTERN( HIX_ECHOCLEAR );
HB_FUNC_EXTERN( HIX_ECHOFLUSH );
HB_FUNC_EXTERN( HIX_ECHOGET );
HB_FUNC_EXTERN( HIX_ERRLOGSEQPEEK );
HB_FUNC_EXTERN( HIX_ERRLOGSEQRESET );
HB_FUNC_EXTERN( HIX_ERRLOGWRITE );
HB_FUNC_EXTERN( HIX_ERRORDESIGNHTMLFORTEST );
HB_FUNC_EXTERN( HIX_ERRORLOGCLOSE );
HB_FUNC_EXTERN( HIX_ERRORLOGINIT );
HB_FUNC_EXTERN( HIX_ERRORNAME );
HB_FUNC_EXTERN( HIX_ERRORSYS );
HB_FUNC_EXTERN( HIX_ERRORSYSDEV );
HB_FUNC_EXTERN( HIX_ERRORSYSFALLBACK );
HB_FUNC_EXTERN( HIX_ERRORSYSINIT );
HB_FUNC_EXTERN( HIX_ERRORSYSPROD );
HB_FUNC_EXTERN( HIX_ERRORVIEW );
HB_FUNC_EXTERN( HIX_EXPRCURLYBALANCEDFORTEST );
HB_FUNC_EXTERN( HIX_FILECONFIG );
HB_FUNC_EXTERN( HIX_FILEROUTE );
HB_FUNC_EXTERN( HIX_FIREWALLCHECK );
HB_FUNC_EXTERN( HIX_FIREWALLCLEAR );
HB_FUNC_EXTERN( HIX_FIREWALLSETUP );
HB_FUNC_EXTERN( HIX_GETCLIENTIP );
HB_FUNC_EXTERN( HIX_GETCONFIG );
HB_FUNC_EXTERN( HIX_GETCONTEXT );
HB_FUNC_EXTERN( HIX_GETERRORHANDLER );
HB_FUNC_EXTERN( HIX_GETLOADERS );
HB_FUNC_EXTERN( HIX_GETMIME );
HB_FUNC_EXTERN( HIX_GETREQUEST );
HB_FUNC_EXTERN( HIX_GETRESOURCE );
HB_FUNC_EXTERN( HIX_GETROOT );
HB_FUNC_EXTERN( HIX_GETROOTABSOLUTE );
HB_FUNC_EXTERN( HIX_GETSTATUS );
HB_FUNC_EXTERN( HIX_GZIPCOMPRESS );
HB_FUNC_EXTERN( HIX_GZIPSHOULDCOMPRESS );
HB_FUNC_EXTERN( HIX_HANDLEWSUPGRADE );
HB_FUNC_EXTERN( HIX_HARBOURCONFIGAPPLY );
HB_FUNC_EXTERN( HIX_HDRSANITIZE );
HB_FUNC_EXTERN( HIX_HDRSTATUSCLAMP );
HB_FUNC_EXTERN( HIX_HELLOPAGE );
HB_FUNC_EXTERN( HIX_HIXSTYLEDORMANT );
HB_FUNC_EXTERN( HIX_HTTPERROR );
HB_FUNC_EXTERN( HIX_HTTPERRORHTML );
HB_FUNC_EXTERN( HIX_INITDEFAULT );
HB_FUNC_EXTERN( HIX_INITLANG );
HB_FUNC_EXTERN( HIX_IPADDR2NUM );
HB_FUNC_EXTERN( HIX_ISFILEPATH );
HB_FUNC_EXTERN( HIX_ISHIXPATH );
HB_FUNC_EXTERN( HIX_ISIPINRANGES );
HB_FUNC_EXTERN( HIX_ISPROXIED );
HB_FUNC_EXTERN( HIX_ISPUBLICIP );
HB_FUNC_EXTERN( HIX_ISRUNNING );
HB_FUNC_EXTERN( HIX_ISSAFEPATH );
HB_FUNC_EXTERN( HIX_ISTRUSTEDPROXY );
HB_FUNC_EXTERN( HIX_JSONDEPTHFORTEST );
HB_FUNC_EXTERN( HIX_JWTALGALLOWED );
HB_FUNC_EXTERN( HIX_JWTAUD );
HB_FUNC_EXTERN( HIX_JWTCONSTANTEQ );
HB_FUNC_EXTERN( HIX_JWTDEFAULTEXP );
HB_FUNC_EXTERN( HIX_JWTDEFAULTKEY );
HB_FUNC_EXTERN( HIX_JWTENCODE );
HB_FUNC_EXTERN( HIX_JWTENCODECUSTOM );
HB_FUNC_EXTERN( HIX_JWTLEEWAY );
HB_FUNC_EXTERN( HIX_JWTPAYLOAD );
HB_FUNC_EXTERN( HIX_JWTVALIDATE );
HB_FUNC_EXTERN( HIX_KEYEXISTS );
HB_FUNC_EXTERN( HIX_KEYGET );
HB_FUNC_EXTERN( HIX_KEYSASHASH );
HB_FUNC_EXTERN( HIX_KEYSET );
HB_FUNC_EXTERN( HIX_KEYSLOADFROMAPPCONFIG );
HB_FUNC_EXTERN( HIX_KEYSRESET );
HB_FUNC_EXTERN( HIX_LANGSELECT );
HB_FUNC_EXTERN( HIX_LIFECYCLEEMITFORTEST );
HB_FUNC_EXTERN( HIX_LOADCONFIG );
HB_FUNC_EXTERN( HIX_LOADCONFIGAPP );
HB_FUNC_EXTERN( HIX_LOADERISUSERFUNC );
HB_FUNC_EXTERN( HIX_LOADERS );
HB_FUNC_EXTERN( HIX_LOADMIDDLEWARE );
HB_FUNC_EXTERN( HIX_LOADROUTES );
HB_FUNC_EXTERN( HIX_LOGGERCLOSE );
HB_FUNC_EXTERN( HIX_LOGGERINIT );
HB_FUNC_EXTERN( HIX_LOGLEVELFROMSTR );
HB_FUNC_EXTERN( HIX_LONGPOLLCOUNT );
HB_FUNC_EXTERN( HIX_LONGPOLLPUSH );
HB_FUNC_EXTERN( HIX_LONGPOLLSETUP );
HB_FUNC_EXTERN( HIX_METRIC );
HB_FUNC_EXTERN( HIX_METRICDEC );
HB_FUNC_EXTERN( HIX_METRICGET );
HB_FUNC_EXTERN( HIX_METRICSCLOSE );
HB_FUNC_EXTERN( HIX_METRICSDUMP );
HB_FUNC_EXTERN( HIX_METRICSET );
HB_FUNC_EXTERN( HIX_METRICSINIT );
HB_FUNC_EXTERN( HIX_METRICSJSON );
HB_FUNC_EXTERN( HIX_METRICSRESET );
HB_FUNC_EXTERN( HIX_METRICSSETTOPN );
HB_FUNC_EXTERN( HIX_METRICTIMING );
HB_FUNC_EXTERN( HIX_METRICTIMINGDYN );
HB_FUNC_EXTERN( HIX_METRICTIMINGSTAT );
HB_FUNC_EXTERN( HIX_METRICWSTIMING );
HB_FUNC_EXTERN( HIX_MIMEEXPAND );
HB_FUNC_EXTERN( HIX_MONITORSTART );
HB_FUNC_EXTERN( HIX_MONITORSTOP );
HB_FUNC_EXTERN( HIX_MPSANITIZEFILENAME );
HB_FUNC_EXTERN( HIX_MWANOMALY );
HB_FUNC_EXTERN( HIX_MWANOMALYSETUP );
HB_FUNC_EXTERN( HIX_MWAPIKEY );
HB_FUNC_EXTERN( HIX_MWAPIKEYFACTORY );
HB_FUNC_EXTERN( HIX_MWAPIKEYSETUP );
HB_FUNC_EXTERN( HIX_MWAUTH );
HB_FUNC_EXTERN( HIX_MWAUTHSETUP );
HB_FUNC_EXTERN( HIX_MWBODYLIMIT );
HB_FUNC_EXTERN( HIX_MWBODYLIMITFACTORY );
HB_FUNC_EXTERN( HIX_MWBODYLIMITSETUP );
HB_FUNC_EXTERN( HIX_MWCONFIG );
HB_FUNC_EXTERN( HIX_MWCORS );
HB_FUNC_EXTERN( HIX_MWCORSCONFIG );
HB_FUNC_EXTERN( HIX_MWCORSSETUP );
HB_FUNC_EXTERN( HIX_MWCORSWILDCARDAUTHCONFLICT );
HB_FUNC_EXTERN( HIX_MWCSRF );
HB_FUNC_EXTERN( HIX_MWCSRFCHECK );
HB_FUNC_EXTERN( HIX_MWCSRFSETUP );
HB_FUNC_EXTERN( HIX_MWHASROLE );
HB_FUNC_EXTERN( HIX_MWISAUTH );
HB_FUNC_EXTERN( HIX_MWJWT );
HB_FUNC_EXTERN( HIX_MWJWTCONFIG );
HB_FUNC_EXTERN( HIX_MWJWTFACTORY );
HB_FUNC_EXTERN( HIX_MWJWTSCOPE );
HB_FUNC_EXTERN( HIX_MWJWTSETUP );
HB_FUNC_EXTERN( HIX_MWLOAD );
HB_FUNC_EXTERN( HIX_MWLOADDIR );
HB_FUNC_EXTERN( HIX_MWMAINTENANCE );
HB_FUNC_EXTERN( HIX_MWMAINTENANCEFACTORY );
HB_FUNC_EXTERN( HIX_MWMAINTENANCESETUP );
HB_FUNC_EXTERN( HIX_MWMETHODFILTER );
HB_FUNC_EXTERN( HIX_MWMETHODFILTERCONFIG );
HB_FUNC_EXTERN( HIX_MWMETHODFILTERFACTORY );
HB_FUNC_EXTERN( HIX_MWMETHODFILTERSETUP );
HB_FUNC_EXTERN( HIX_MWRATELIMIT );
HB_FUNC_EXTERN( HIX_MWRATELIMITCONFIG );
HB_FUNC_EXTERN( HIX_MWRATELIMITFACTORY );
HB_FUNC_EXTERN( HIX_MWRATELIMITSETUP );
HB_FUNC_EXTERN( HIX_MWREQLOG );
HB_FUNC_EXTERN( HIX_MWREQLOGFACTORY );
HB_FUNC_EXTERN( HIX_MWREQLOGSETUP );
HB_FUNC_EXTERN( HIX_MWREQUIREAUTH );
HB_FUNC_EXTERN( HIX_MWSECHEADERS );
HB_FUNC_EXTERN( HIX_MWSECHEADERSFACTORY );
HB_FUNC_EXTERN( HIX_MWSECHEADERSSETUP );
HB_FUNC_EXTERN( HIX_MWSESSION );
HB_FUNC_EXTERN( HIX_MWSESSIONCONFIG );
HB_FUNC_EXTERN( HIX_MWSESSIONSETROUTE );
HB_FUNC_EXTERN( HIX_MWSESSIONSETUP );
HB_FUNC_EXTERN( HIX_MWUNLOAD );
HB_FUNC_EXTERN( HIX_NAVIGATOR );
HB_FUNC_EXTERN( HIX_NEWERROR );
HB_FUNC_EXTERN( HIX_OPTFUNC );
HB_FUNC_EXTERN( HIX_PARSEFIREWALLFILTER );
HB_FUNC_EXTERN( HIX_PARSEFORWARDED );
HB_FUNC_EXTERN( HIX_PARSEMULTIPART );
HB_FUNC_EXTERN( HIX_PARSER );
HB_FUNC_EXTERN( HIX_PATHISUNDERROOT );
HB_FUNC_EXTERN( HIX_PATHNORMALIZE );
HB_FUNC_EXTERN( HIX_PATHVIEWS );
HB_FUNC_EXTERN( HIX_PATTERNTOREGEXPFORTEST );
HB_FUNC_EXTERN( HIX_POOLCREATE );
HB_FUNC_EXTERN( HIX_POOLDEL );
HB_FUNC_EXTERN( HIX_POOLDELRAW );
HB_FUNC_EXTERN( HIX_POOLDESTROY );
HB_FUNC_EXTERN( HIX_POOLEXISTS );
HB_FUNC_EXTERN( HIX_POOLGET );
HB_FUNC_EXTERN( HIX_POOLGETRAW );
HB_FUNC_EXTERN( HIX_POOLHAS );
HB_FUNC_EXTERN( HIX_POOLHASRAW );
HB_FUNC_EXTERN( HIX_POOLKEYS );
HB_FUNC_EXTERN( HIX_POOLKEYSRAW );
HB_FUNC_EXTERN( HIX_POOLLOCK );
HB_FUNC_EXTERN( HIX_POOLSET );
HB_FUNC_EXTERN( HIX_POOLSETRAW );
HB_FUNC_EXTERN( HIX_POOLSIZE );
HB_FUNC_EXTERN( HIX_POOLUNLOCK );
HB_FUNC_EXTERN( HIX_PREAMBLELINES );
HB_FUNC_EXTERN( HIX_PRGROUTE );
HB_FUNC_EXTERN( HIX_PROXYINIT );
HB_FUNC_EXTERN( HIX_RATELIMITESTIMATE );
HB_FUNC_EXTERN( HIX_REGEXESCAPE );
HB_FUNC_EXTERN( HIX_RESOURCEHTML );
HB_FUNC_EXTERN( HIX_RESPONSERAW );
HB_FUNC_EXTERN( HIX_RESPONSESTREAMSTART );
HB_FUNC_EXTERN( HIX_ROUTEADD );
HB_FUNC_EXTERN( HIX_ROUTEDELETE );
HB_FUNC_EXTERN( HIX_ROUTEDISPATCH );
HB_FUNC_EXTERN( HIX_ROUTEDISPREF );
HB_FUNC_EXTERN( HIX_ROUTEDISPRESET );
HB_FUNC_EXTERN( HIX_ROUTEGETACTION );
HB_FUNC_EXTERN( HIX_ROUTEGROUP );
HB_FUNC_EXTERN( HIX_ROUTEHASACTION );
HB_FUNC_EXTERN( HIX_ROUTELIST );
HB_FUNC_EXTERN( HIX_ROUTEPARAM );
HB_FUNC_EXTERN( HIX_ROUTEREGISTERACTION );
HB_FUNC_EXTERN( HIX_ROUTESETHANDLER );
HB_FUNC_EXTERN( HIX_ROUTESISINIT );
HB_FUNC_EXTERN( HIX_ROUTESLOAD );
HB_FUNC_EXTERN( HIX_ROUTESRESTORE );
HB_FUNC_EXTERN( HIX_ROUTESSNAPSHOT );
HB_FUNC_EXTERN( HIX_SAFEDIRDELETE );
HB_FUNC_EXTERN( HIX_SAFEERASE );
HB_FUNC_EXTERN( HIX_SAFEPATHALLOWED );
HB_FUNC_EXTERN( HIX_SAFEREGISTERDIR );
HB_FUNC_EXTERN( HIX_SAVECONFIG );
HB_FUNC_EXTERN( HIX_SERVERDORMANTHIXSTYLEFORTEST );
HB_FUNC_EXTERN( HIX_SERVERISRUNNING );
HB_FUNC_EXTERN( HIX_SERVERLIFECYCLEFORTEST );
HB_FUNC_EXTERN( HIX_SERVERMUTEXREADYFORTEST );
HB_FUNC_EXTERN( HIX_SERVERPROXIEDFORTEST );
HB_FUNC_EXTERN( HIX_SERVERREQUESTSTOP );
HB_FUNC_EXTERN( HIX_SERVERREQUESTSTOPCLEARFORTEST );
HB_FUNC_EXTERN( HIX_SERVERSETDORMANTHIXSTYLEFORTEST );
HB_FUNC_EXTERN( HIX_SERVERSTOPREQUESTEDFORTEST );
HB_FUNC_EXTERN( HIX_SESSION );
HB_FUNC_EXTERN( HIX_SESSIONDESTROY );
HB_FUNC_EXTERN( HIX_SESSIONFILEGCFORTEST );
HB_FUNC_EXTERN( HIX_SESSIONFILELOADFORTEST );
HB_FUNC_EXTERN( HIX_SESSIONFILEWRITEFORTEST );
HB_FUNC_EXTERN( HIX_SESSIONGET );
HB_FUNC_EXTERN( HIX_SESSIONMEMSETFORTEST );
HB_FUNC_EXTERN( HIX_SESSIONNEWID );
HB_FUNC_EXTERN( HIX_SESSIONROTATE );
HB_FUNC_EXTERN( HIX_SESSIONSAVE );
HB_FUNC_EXTERN( HIX_SESSIONSET );
HB_FUNC_EXTERN( HIX_SETCONFIG );
HB_FUNC_EXTERN( HIX_SETCONTEXT );
HB_FUNC_EXTERN( HIX_SETCOOKIE );
HB_FUNC_EXTERN( HIX_SETERRORHANDLER );
HB_FUNC_EXTERN( HIX_SETLIFECYCLEHOOK );
HB_FUNC_EXTERN( HIX_SETMIME );
HB_FUNC_EXTERN( HIX_SETREQUEST );
HB_FUNC_EXTERN( HIX_SETSTATUS );
HB_FUNC_EXTERN( HIX_SHOWERROR );
HB_FUNC_EXTERN( HIX_SOCKETCONFIGURE );
HB_FUNC_EXTERN( HIX_SOCKETINIT );
HB_FUNC_EXTERN( HIX_SOCKETPEEK );
HB_FUNC_EXTERN( HIX_SOCKETPEEKSSL );
HB_FUNC_EXTERN( HIX_SSEBROADCAST );
HB_FUNC_EXTERN( HIX_SSECOUNT );
HB_FUNC_EXTERN( HIX_SSESETUP );
HB_FUNC_EXTERN( HIX_STATUSTEXT );
HB_FUNC_EXTERN( HIX_SUBVERSION );
HB_FUNC_EXTERN( HIX_THROW );
HB_FUNC_EXTERN( HIX_TIMEOUTSEC );
HB_FUNC_EXTERN( HIX_TOKENCONSTANTEQ );
HB_FUNC_EXTERN( HIX_TOKENGENRANDOM );
HB_FUNC_EXTERN( HIX_TOKENGETSECRET );
HB_FUNC_EXTERN( HIX_TOKENMAKE );
HB_FUNC_EXTERN( HIX_TOKENSETSECRET );
HB_FUNC_EXTERN( HIX_TOKENVALID );
HB_FUNC_EXTERN( HIX_TRACEALL );
HB_FUNC_EXTERN( HIX_TRACEENABLED );
HB_FUNC_EXTERN( HIX_TRACEGETALL );
HB_FUNC_EXTERN( HIX_TRACESET );
HB_FUNC_EXTERN( HIX_TRANSPILE );
HB_FUNC_EXTERN( HIX_URLDECODE );
HB_FUNC_EXTERN( HIX_USEREXIT );
HB_FUNC_EXTERN( HIX_USERINIT );
HB_FUNC_EXTERN( HIX_VALCAST );
HB_FUNC_EXTERN( HIX_VALCHECK );
HB_FUNC_EXTERN( HIX_VALIDCONFIG );
HB_FUNC_EXTERN( HIX_VALIDIP );
HB_FUNC_EXTERN( HIX_VALSANITIZE );
HB_FUNC_EXTERN( HIX_VERSION );
HB_FUNC_EXTERN( HIX_VIEWCACHECLEAR );
HB_FUNC_EXTERN( HIX_VIEWCACHEINIT );
HB_FUNC_EXTERN( HIX_VIEW_PARAMS );
HB_FUNC_EXTERN( HIX_VIEW_VIEWER );
HB_FUNC_EXTERN( HIX_WANTSJSON );
HB_FUNC_EXTERN( HIX_WAPISTUBS_DUMMY );
HB_FUNC_EXTERN( HIX_WORKERHTTP );
HB_FUNC_EXTERN( HIX_WORKERPROTECT );
HB_FUNC_EXTERN( HIX_WORKERREST );
HB_FUNC_EXTERN( HIX_WORKERWS );
HB_FUNC_EXTERN( HIX_WSBUILDFRAME );
HB_FUNC_EXTERN( HIX_WSGETCALLBACKS );
HB_FUNC_EXTERN( HIX_WSSAFEEVAL );
HB_FUNC_EXTERN( HIX_WSSETCALLBACKS );
HB_FUNC_EXTERN( HIX_WSTESTBUILDCLIENTFRAME );
HB_FUNC_EXTERN( HIX_WSTESTRUNFRAMELOOP );
HB_FUNC_EXTERN( HIX_ZOMBIEADD );
HB_FUNC_EXTERN( HIX_ZOMBIECOUNT );
HB_FUNC_EXTERN( HIX_ZOMBIEDEAD );
HB_FUNC_EXTERN( HIX_ZOMBIEINIT );
HB_FUNC_EXTERN( HIX_ZOMBIEOVERLOAD );
HB_FUNC_EXTERN( HIX_ZOMBIEPURGE );
HB_FUNC_EXTERN( HIX_ZOMBIEREPORT );
HB_FUNC_EXTERN( LANGSTRINGS_EN );
HB_FUNC_EXTERN( LANGSTRINGS_ES );
HB_FUNC_EXTERN( MW_API_ADMIN );
HB_FUNC_EXTERN( MW_API_JWT );
HB_FUNC_EXTERN( MW_WEB_ADMIN );
HB_FUNC_EXTERN( MW_WEB_AUTH );
HB_FUNC_EXTERN( MW_WEB_EDIT );
HB_FUNC_EXTERN( MW_WEB_SESSION );
HB_FUNC_EXTERN( SETHARUFONTDIR );
HB_FUNC_EXTERN( SHOWERROR );
HB_FUNC_EXTERN( TFLASH );
HB_FUNC_EXTERN( THIXCONTEXT );
HB_FUNC_EXTERN( THIXDISPATCHER );
HB_FUNC_EXTERN( THIXERROR );
HB_FUNC_EXTERN( THIXIO );
HB_FUNC_EXTERN( THIXLOGGER );
HB_FUNC_EXTERN( THIXMETRICS );
HB_FUNC_EXTERN( THIXPOOL );
HB_FUNC_EXTERN( THIXREQUEST );
HB_FUNC_EXTERN( THIXSERVER );
HB_FUNC_EXTERN( THIXSESSIONPROXY );
HB_FUNC_EXTERN( THIXSOCKET );
HB_FUNC_EXTERN( THIXSSECONN );
HB_FUNC_EXTERN( THIXVALIDATOR );
HB_FUNC_EXTERN( THIXWSCONN );
HB_FUNC_EXTERN( TPDF );
HB_FUNC_EXTERN( UAUTHLOGOUT );
HB_FUNC_EXTERN( UAUTHUSER );
HB_FUNC_EXTERN( UBASEMIDDLEWARE );
HB_FUNC_EXTERN( UBODY );
HB_FUNC_EXTERN( UCONFIG );
HB_FUNC_EXTERN( UCONTENTLENGTH );
HB_FUNC_EXTERN( UCONTENTTYPE );
HB_FUNC_EXTERN( UCONTEXT );
HB_FUNC_EXTERN( UCOOKIE );
HB_FUNC_EXTERN( UCSRFTOHTML );
HB_FUNC_EXTERN( UCURL );
HB_FUNC_EXTERN( UCURRENTUSER );
HB_FUNC_EXTERN( UDATETOHTML );
HB_FUNC_EXTERN( UDBF );
HB_FUNC_EXTERN( UECHO );
HB_FUNC_EXTERN( UENV );
HB_FUNC_EXTERN( UERRORPAGE );
HB_FUNC_EXTERN( UFILES );
HB_FUNC_EXTERN( UFLASH );
HB_FUNC_EXTERN( UFLUSH );
HB_FUNC_EXTERN( UGET );
HB_FUNC_EXTERN( UGETCONFIG );
HB_FUNC_EXTERN( UGETMIME );
HB_FUNC_EXTERN( UGETPPRULES );
HB_FUNC_EXTERN( UGETRESOURCE );
HB_FUNC_EXTERN( UGETROLES );
HB_FUNC_EXTERN( UHASHTOHTMLSELECT );
HB_FUNC_EXTERN( UHASROLE );
HB_FUNC_EXTERN( UHASSCOPE );
HB_FUNC_EXTERN( UHEADER );
HB_FUNC_EXTERN( UHOST );
HB_FUNC_EXTERN( UHTMLENCODE );
HB_FUNC_EXTERN( UIP );
HB_FUNC_EXTERN( UISAJAX );
HB_FUNC_EXTERN( UISDEV );
HB_FUNC_EXTERN( UISFORM );
HB_FUNC_EXTERN( UISGET );
HB_FUNC_EXTERN( UISHTTPS );
HB_FUNC_EXTERN( UISINTEGER );
HB_FUNC_EXTERN( UISIP );
HB_FUNC_EXTERN( UISJSON );
HB_FUNC_EXTERN( UISMAIL );
HB_FUNC_EXTERN( UISMULTIPART );
HB_FUNC_EXTERN( UISNUMERIC );
HB_FUNC_EXTERN( UISPOST );
HB_FUNC_EXTERN( UISPROD );
HB_FUNC_EXTERN( UISURL );
HB_FUNC_EXTERN( UJSON );
HB_FUNC_EXTERN( UJWT );
HB_FUNC_EXTERN( ULOGICTOHTMLCHECKED );
HB_FUNC_EXTERN( UMETHOD );
HB_FUNC_EXTERN( UMIDDLEWARE );
HB_FUNC_EXTERN( UMWCONFIG );
HB_FUNC_EXTERN( UNOW );
HB_FUNC_EXTERN( UOSFILENAME );
HB_FUNC_EXTERN( UPARAM );
HB_FUNC_EXTERN( UPATH );
HB_FUNC_EXTERN( UPEERALIVE );
HB_FUNC_EXTERN( UPORT );
HB_FUNC_EXTERN( UPOST );
HB_FUNC_EXTERN( UPROD );
HB_FUNC_EXTERN( UQUERY );
HB_FUNC_EXTERN( UREDIRECT );
HB_FUNC_EXTERN( UREQUEST );
HB_FUNC_EXTERN( URESOURCETOHTML );
HB_FUNC_EXTERN( UROOT );
HB_FUNC_EXTERN( UROOTPATH );
HB_FUNC_EXTERN( UROUTE );
HB_FUNC_EXTERN( USCHEME );
HB_FUNC_EXTERN( USEND );
HB_FUNC_EXTERN( USENDCHUNK );
HB_FUNC_EXTERN( USENDEMPTY );
HB_FUNC_EXTERN( USENDERROR );
HB_FUNC_EXTERN( USENDHTML );
HB_FUNC_EXTERN( USENDJSON );
HB_FUNC_EXTERN( USENDSTREAMEND );
HB_FUNC_EXTERN( USENDSTREAMSTART );
HB_FUNC_EXTERN( USENDTEXT );
HB_FUNC_EXTERN( USENDVIEW );
HB_FUNC_EXTERN( USESSION );
HB_FUNC_EXTERN( USESSIONROTATE );
HB_FUNC_EXTERN( USETCOOKIE );
HB_FUNC_EXTERN( USETHEADER );
HB_FUNC_EXTERN( USETMIME );
HB_FUNC_EXTERN( USETSTATUS );
HB_FUNC_EXTERN( USTR );
HB_FUNC_EXTERN( UVALIDATEGET );
HB_FUNC_EXTERN( UVALIDATEJSON );
HB_FUNC_EXTERN( UVALIDATEORFAIL );
HB_FUNC_EXTERN( UVALIDATEPARAMS );
HB_FUNC_EXTERN( UVALIDATEPOST );
HB_FUNC_EXTERN( UVALIDATOR );
HB_FUNC_EXTERN( UVALIDATORONE );
HB_FUNC_EXTERN( UVIEW );
HB_FUNC_EXTERN( UVIEW_CSS );
HB_FUNC_EXTERN( UVIEW_EXEC );
HB_FUNC_EXTERN( UVIEW_JS );
HB_FUNC_EXTERN( UWANTSJSON );
HB_FUNC_EXTERN( UWRITE );
HB_FUNC_EXTERN( WAPI_OUTPUTDEBUGSTRING );
HB_FUNC_EXTERN( WAPI_SHELLEXECUTE );
HB_FUNC_EXTERN( _ );
HB_FUNC_EXTERN( _C );
HB_FUNC_EXTERN( _D );
HB_FUNC_EXTERN( _HIXLPWAIT );
HB_FUNC_EXTERN( _HIXROUTESETSOURCE );
HB_FUNC_EXTERN( _HIXSSEREGISTER );
HB_FUNC_EXTERN( _HIXSSEUNREGISTER );
HB_FUNC_EXTERN( _L );
HB_FUNC_EXTERN( _STACK );
HB_FUNC_EXTERN( _T );
HB_FUNC_EXTERN( _W );
HB_FUNC( __HBEXTERN__HIX_SERVER__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_HIX_SERVER )
{ "GETHARUFONTDIR", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETHARUFONTDIR )}, NULL },
{ "GETHARUFONTLIST", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETHARUFONTLIST )}, NULL },
{ "HARUADDFONT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HARUADDFONT )}, NULL },
{ "HIXSHOULDABORT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIXSHOULDABORT )}, NULL },
{ "HIX_ACCESSLOG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ACCESSLOG )}, NULL },
{ "HIX_ACCESSLOGCLOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ACCESSLOGCLOSE )}, NULL },
{ "HIX_ACCESSLOGINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ACCESSLOGINIT )}, NULL },
{ "HIX_ADMINCHECK", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ADMINCHECK )}, NULL },
{ "HIX_ADMINLOGINGET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ADMINLOGINGET )}, NULL },
{ "HIX_ADMINLOGINPOST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ADMINLOGINPOST )}, NULL },
{ "HIX_ADMINLOGOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ADMINLOGOUT )}, NULL },
{ "HIX_ADMINSETUPGET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ADMINSETUPGET )}, NULL },
{ "HIX_ADMINSETUPPOST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ADMINSETUPPOST )}, NULL },
{ "HIX_ANOMALYRECORD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ANOMALYRECORD )}, NULL },
{ "HIX_ANOMALYSTATS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ANOMALYSTATS )}, NULL },
{ "HIX_APPCONFIG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_APPCONFIG )}, NULL },
{ "HIX_APPROOT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_APPROOT )}, NULL },
{ "HIX_BLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_BLOCK )}, NULL },
{ "HIX_BOOTLOG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_BOOTLOG )}, NULL },
{ "HIX_BOOTLOGACTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_BOOTLOGACTION )}, NULL },
{ "HIX_BOOTLOGADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_BOOTLOGADD )}, NULL },
{ "HIX_BOOTLOGISVERBOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_BOOTLOGISVERBOSE )}, NULL },
{ "HIX_BOOTLOGRESET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_BOOTLOGRESET )}, NULL },
{ "HIX_BOOTLOGSECTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_BOOTLOGSECTION )}, NULL },
{ "HIX_BOOTLOGSHOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_BOOTLOGSHOW )}, NULL },
{ "HIX_BOOTLOGVERBOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_BOOTLOGVERBOSE )}, NULL },
{ "HIX_CLOSEDBFAREAS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_CLOSEDBFAREAS )}, NULL },
{ "HIX_COMPILEFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_COMPILEFILE )}, NULL },
{ "HIX_CONFIGAPP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_CONFIGAPP )}, NULL },
{ "HIX_CONFIGAPPDEFAULTS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_CONFIGAPPDEFAULTS )}, NULL },
{ "HIX_CONFIGAPPLOAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_CONFIGAPPLOAD )}, NULL },
{ "HIX_CONFIGAPPMERGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_CONFIGAPPMERGE )}, NULL },
{ "HIX_CONFIGAPPRESET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_CONFIGAPPRESET )}, NULL },
{ "HIX_CONFIGAPPSAVE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_CONFIGAPPSAVE )}, NULL },
{ "HIX_CONFIGAPPSET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_CONFIGAPPSET )}, NULL },
{ "HIX_CONFIGMERGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_CONFIGMERGE )}, NULL },
{ "HIX_CONSTANTEQ", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_CONSTANTEQ )}, NULL },
{ "HIX_CSRFGENRANDOM", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_CSRFGENRANDOM )}, NULL },
{ "HIX_CSRFMAKETOKEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_CSRFMAKETOKEN )}, NULL },
{ "HIX_CSRFVALIDTOKEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_CSRFVALIDTOKEN )}, NULL },
{ "HIX_DATECOMPILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_DATECOMPILE )}, NULL },
{ "HIX_DBF", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_DBF )}, NULL },
{ "HIX_DBG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_DBG )}, NULL },
{ "HIX_DBGERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_DBGERROR )}, NULL },
{ "HIX_DBGRESET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_DBGRESET )}, NULL },
{ "HIX_DBGSETFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_DBGSETFILE )}, NULL },
{ "HIX_DETECTPROTOCOL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_DETECTPROTOCOL )}, NULL },
{ "HIX_DOERRORVIEW", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_DOERRORVIEW )}, NULL },
{ "HIX_ECHO", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ECHO )}, NULL },
{ "HIX_ECHOCLEAR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ECHOCLEAR )}, NULL },
{ "HIX_ECHOFLUSH", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ECHOFLUSH )}, NULL },
{ "HIX_ECHOGET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ECHOGET )}, NULL },
{ "HIX_ERRLOGSEQPEEK", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ERRLOGSEQPEEK )}, NULL },
{ "HIX_ERRLOGSEQRESET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ERRLOGSEQRESET )}, NULL },
{ "HIX_ERRLOGWRITE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ERRLOGWRITE )}, NULL },
{ "HIX_ERRORDESIGNHTMLFORTEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ERRORDESIGNHTMLFORTEST )}, NULL },
{ "HIX_ERRORLOGCLOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ERRORLOGCLOSE )}, NULL },
{ "HIX_ERRORLOGINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ERRORLOGINIT )}, NULL },
{ "HIX_ERRORNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ERRORNAME )}, NULL },
{ "HIX_ERRORSYS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ERRORSYS )}, NULL },
{ "HIX_ERRORSYSDEV", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ERRORSYSDEV )}, NULL },
{ "HIX_ERRORSYSFALLBACK", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ERRORSYSFALLBACK )}, NULL },
{ "HIX_ERRORSYSINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ERRORSYSINIT )}, NULL },
{ "HIX_ERRORSYSPROD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ERRORSYSPROD )}, NULL },
{ "HIX_ERRORVIEW", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ERRORVIEW )}, NULL },
{ "HIX_EXPRCURLYBALANCEDFORTEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_EXPRCURLYBALANCEDFORTEST )}, NULL },
{ "HIX_FILECONFIG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_FILECONFIG )}, NULL },
{ "HIX_FILEROUTE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_FILEROUTE )}, NULL },
{ "HIX_FIREWALLCHECK", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_FIREWALLCHECK )}, NULL },
{ "HIX_FIREWALLCLEAR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_FIREWALLCLEAR )}, NULL },
{ "HIX_FIREWALLSETUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_FIREWALLSETUP )}, NULL },
{ "HIX_GETCLIENTIP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_GETCLIENTIP )}, NULL },
{ "HIX_GETCONFIG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_GETCONFIG )}, NULL },
{ "HIX_GETCONTEXT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_GETCONTEXT )}, NULL },
{ "HIX_GETERRORHANDLER", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_GETERRORHANDLER )}, NULL },
{ "HIX_GETLOADERS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_GETLOADERS )}, NULL },
{ "HIX_GETMIME", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_GETMIME )}, NULL },
{ "HIX_GETREQUEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_GETREQUEST )}, NULL },
{ "HIX_GETRESOURCE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_GETRESOURCE )}, NULL },
{ "HIX_GETROOT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_GETROOT )}, NULL },
{ "HIX_GETROOTABSOLUTE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_GETROOTABSOLUTE )}, NULL },
{ "HIX_GETSTATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_GETSTATUS )}, NULL },
{ "HIX_GZIPCOMPRESS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_GZIPCOMPRESS )}, NULL },
{ "HIX_GZIPSHOULDCOMPRESS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_GZIPSHOULDCOMPRESS )}, NULL },
{ "HIX_HANDLEWSUPGRADE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_HANDLEWSUPGRADE )}, NULL },
{ "HIX_HARBOURCONFIGAPPLY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_HARBOURCONFIGAPPLY )}, NULL },
{ "HIX_HDRSANITIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_HDRSANITIZE )}, NULL },
{ "HIX_HDRSTATUSCLAMP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_HDRSTATUSCLAMP )}, NULL },
{ "HIX_HELLOPAGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_HELLOPAGE )}, NULL },
{ "HIX_HIXSTYLEDORMANT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_HIXSTYLEDORMANT )}, NULL },
{ "HIX_HTTPERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_HTTPERROR )}, NULL },
{ "HIX_HTTPERRORHTML", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_HTTPERRORHTML )}, NULL },
{ "HIX_INITDEFAULT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_INITDEFAULT )}, NULL },
{ "HIX_INITLANG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_INITLANG )}, NULL },
{ "HIX_IPADDR2NUM", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_IPADDR2NUM )}, NULL },
{ "HIX_ISFILEPATH", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ISFILEPATH )}, NULL },
{ "HIX_ISHIXPATH", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ISHIXPATH )}, NULL },
{ "HIX_ISIPINRANGES", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ISIPINRANGES )}, NULL },
{ "HIX_ISPROXIED", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ISPROXIED )}, NULL },
{ "HIX_ISPUBLICIP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ISPUBLICIP )}, NULL },
{ "HIX_ISRUNNING", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ISRUNNING )}, NULL },
{ "HIX_ISSAFEPATH", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ISSAFEPATH )}, NULL },
{ "HIX_ISTRUSTEDPROXY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ISTRUSTEDPROXY )}, NULL },
{ "HIX_JSONDEPTHFORTEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_JSONDEPTHFORTEST )}, NULL },
{ "HIX_JWTALGALLOWED", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_JWTALGALLOWED )}, NULL },
{ "HIX_JWTAUD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_JWTAUD )}, NULL },
{ "HIX_JWTCONSTANTEQ", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_JWTCONSTANTEQ )}, NULL },
{ "HIX_JWTDEFAULTEXP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_JWTDEFAULTEXP )}, NULL },
{ "HIX_JWTDEFAULTKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_JWTDEFAULTKEY )}, NULL },
{ "HIX_JWTENCODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_JWTENCODE )}, NULL },
{ "HIX_JWTENCODECUSTOM", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_JWTENCODECUSTOM )}, NULL },
{ "HIX_JWTLEEWAY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_JWTLEEWAY )}, NULL },
{ "HIX_JWTPAYLOAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_JWTPAYLOAD )}, NULL },
{ "HIX_JWTVALIDATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_JWTVALIDATE )}, NULL },
{ "HIX_KEYEXISTS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_KEYEXISTS )}, NULL },
{ "HIX_KEYGET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_KEYGET )}, NULL },
{ "HIX_KEYSASHASH", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_KEYSASHASH )}, NULL },
{ "HIX_KEYSET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_KEYSET )}, NULL },
{ "HIX_KEYSLOADFROMAPPCONFIG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_KEYSLOADFROMAPPCONFIG )}, NULL },
{ "HIX_KEYSRESET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_KEYSRESET )}, NULL },
{ "HIX_LANGSELECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_LANGSELECT )}, NULL },
{ "HIX_LIFECYCLEEMITFORTEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_LIFECYCLEEMITFORTEST )}, NULL },
{ "HIX_LOADCONFIG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_LOADCONFIG )}, NULL },
{ "HIX_LOADCONFIGAPP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_LOADCONFIGAPP )}, NULL },
{ "HIX_LOADERISUSERFUNC", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_LOADERISUSERFUNC )}, NULL },
{ "HIX_LOADERS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_LOADERS )}, NULL },
{ "HIX_LOADMIDDLEWARE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_LOADMIDDLEWARE )}, NULL },
{ "HIX_LOADROUTES", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_LOADROUTES )}, NULL },
{ "HIX_LOGGERCLOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_LOGGERCLOSE )}, NULL },
{ "HIX_LOGGERINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_LOGGERINIT )}, NULL },
{ "HIX_LOGLEVELFROMSTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_LOGLEVELFROMSTR )}, NULL },
{ "HIX_LONGPOLLCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_LONGPOLLCOUNT )}, NULL },
{ "HIX_LONGPOLLPUSH", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_LONGPOLLPUSH )}, NULL },
{ "HIX_LONGPOLLSETUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_LONGPOLLSETUP )}, NULL },
{ "HIX_METRIC", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_METRIC )}, NULL },
{ "HIX_METRICDEC", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_METRICDEC )}, NULL },
{ "HIX_METRICGET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_METRICGET )}, NULL },
{ "HIX_METRICSCLOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_METRICSCLOSE )}, NULL },
{ "HIX_METRICSDUMP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_METRICSDUMP )}, NULL },
{ "HIX_METRICSET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_METRICSET )}, NULL },
{ "HIX_METRICSINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_METRICSINIT )}, NULL },
{ "HIX_METRICSJSON", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_METRICSJSON )}, NULL },
{ "HIX_METRICSRESET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_METRICSRESET )}, NULL },
{ "HIX_METRICSSETTOPN", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_METRICSSETTOPN )}, NULL },
{ "HIX_METRICTIMING", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_METRICTIMING )}, NULL },
{ "HIX_METRICTIMINGDYN", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_METRICTIMINGDYN )}, NULL },
{ "HIX_METRICTIMINGSTAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_METRICTIMINGSTAT )}, NULL },
{ "HIX_METRICWSTIMING", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_METRICWSTIMING )}, NULL },
{ "HIX_MIMEEXPAND", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MIMEEXPAND )}, NULL },
{ "HIX_MONITORSTART", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MONITORSTART )}, NULL },
{ "HIX_MONITORSTOP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MONITORSTOP )}, NULL },
{ "HIX_MPSANITIZEFILENAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MPSANITIZEFILENAME )}, NULL },
{ "HIX_MWANOMALY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWANOMALY )}, NULL },
{ "HIX_MWANOMALYSETUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWANOMALYSETUP )}, NULL },
{ "HIX_MWAPIKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWAPIKEY )}, NULL },
{ "HIX_MWAPIKEYFACTORY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWAPIKEYFACTORY )}, NULL },
{ "HIX_MWAPIKEYSETUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWAPIKEYSETUP )}, NULL },
{ "HIX_MWAUTH", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWAUTH )}, NULL },
{ "HIX_MWAUTHSETUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWAUTHSETUP )}, NULL },
{ "HIX_MWBODYLIMIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWBODYLIMIT )}, NULL },
{ "HIX_MWBODYLIMITFACTORY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWBODYLIMITFACTORY )}, NULL },
{ "HIX_MWBODYLIMITSETUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWBODYLIMITSETUP )}, NULL },
{ "HIX_MWCONFIG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWCONFIG )}, NULL },
{ "HIX_MWCORS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWCORS )}, NULL },
{ "HIX_MWCORSCONFIG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWCORSCONFIG )}, NULL },
{ "HIX_MWCORSSETUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWCORSSETUP )}, NULL },
{ "HIX_MWCORSWILDCARDAUTHCONFLICT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWCORSWILDCARDAUTHCONFLICT )}, NULL },
{ "HIX_MWCSRF", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWCSRF )}, NULL },
{ "HIX_MWCSRFCHECK", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWCSRFCHECK )}, NULL },
{ "HIX_MWCSRFSETUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWCSRFSETUP )}, NULL },
{ "HIX_MWHASROLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWHASROLE )}, NULL },
{ "HIX_MWISAUTH", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWISAUTH )}, NULL },
{ "HIX_MWJWT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWJWT )}, NULL },
{ "HIX_MWJWTCONFIG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWJWTCONFIG )}, NULL },
{ "HIX_MWJWTFACTORY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWJWTFACTORY )}, NULL },
{ "HIX_MWJWTSCOPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWJWTSCOPE )}, NULL },
{ "HIX_MWJWTSETUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWJWTSETUP )}, NULL },
{ "HIX_MWLOAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWLOAD )}, NULL },
{ "HIX_MWLOADDIR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWLOADDIR )}, NULL },
{ "HIX_MWMAINTENANCE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWMAINTENANCE )}, NULL },
{ "HIX_MWMAINTENANCEFACTORY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWMAINTENANCEFACTORY )}, NULL },
{ "HIX_MWMAINTENANCESETUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWMAINTENANCESETUP )}, NULL },
{ "HIX_MWMETHODFILTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWMETHODFILTER )}, NULL },
{ "HIX_MWMETHODFILTERCONFIG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWMETHODFILTERCONFIG )}, NULL },
{ "HIX_MWMETHODFILTERFACTORY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWMETHODFILTERFACTORY )}, NULL },
{ "HIX_MWMETHODFILTERSETUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWMETHODFILTERSETUP )}, NULL },
{ "HIX_MWRATELIMIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWRATELIMIT )}, NULL },
{ "HIX_MWRATELIMITCONFIG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWRATELIMITCONFIG )}, NULL },
{ "HIX_MWRATELIMITFACTORY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWRATELIMITFACTORY )}, NULL },
{ "HIX_MWRATELIMITSETUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWRATELIMITSETUP )}, NULL },
{ "HIX_MWREQLOG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWREQLOG )}, NULL },
{ "HIX_MWREQLOGFACTORY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWREQLOGFACTORY )}, NULL },
{ "HIX_MWREQLOGSETUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWREQLOGSETUP )}, NULL },
{ "HIX_MWREQUIREAUTH", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWREQUIREAUTH )}, NULL },
{ "HIX_MWSECHEADERS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWSECHEADERS )}, NULL },
{ "HIX_MWSECHEADERSFACTORY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWSECHEADERSFACTORY )}, NULL },
{ "HIX_MWSECHEADERSSETUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWSECHEADERSSETUP )}, NULL },
{ "HIX_MWSESSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWSESSION )}, NULL },
{ "HIX_MWSESSIONCONFIG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWSESSIONCONFIG )}, NULL },
{ "HIX_MWSESSIONSETROUTE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWSESSIONSETROUTE )}, NULL },
{ "HIX_MWSESSIONSETUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWSESSIONSETUP )}, NULL },
{ "HIX_MWUNLOAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_MWUNLOAD )}, NULL },
{ "HIX_NAVIGATOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_NAVIGATOR )}, NULL },
{ "HIX_NEWERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_NEWERROR )}, NULL },
{ "HIX_OPTFUNC", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_OPTFUNC )}, NULL },
{ "HIX_PARSEFIREWALLFILTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_PARSEFIREWALLFILTER )}, NULL },
{ "HIX_PARSEFORWARDED", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_PARSEFORWARDED )}, NULL },
{ "HIX_PARSEMULTIPART", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_PARSEMULTIPART )}, NULL },
{ "HIX_PARSER", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_PARSER )}, NULL },
{ "HIX_PATHISUNDERROOT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_PATHISUNDERROOT )}, NULL },
{ "HIX_PATHNORMALIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_PATHNORMALIZE )}, NULL },
{ "HIX_PATHVIEWS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_PATHVIEWS )}, NULL },
{ "HIX_PATTERNTOREGEXPFORTEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_PATTERNTOREGEXPFORTEST )}, NULL },
{ "HIX_POOLCREATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_POOLCREATE )}, NULL },
{ "HIX_POOLDEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_POOLDEL )}, NULL },
{ "HIX_POOLDELRAW", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_POOLDELRAW )}, NULL },
{ "HIX_POOLDESTROY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_POOLDESTROY )}, NULL },
{ "HIX_POOLEXISTS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_POOLEXISTS )}, NULL },
{ "HIX_POOLGET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_POOLGET )}, NULL },
{ "HIX_POOLGETRAW", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_POOLGETRAW )}, NULL },
{ "HIX_POOLHAS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_POOLHAS )}, NULL },
{ "HIX_POOLHASRAW", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_POOLHASRAW )}, NULL },
{ "HIX_POOLKEYS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_POOLKEYS )}, NULL },
{ "HIX_POOLKEYSRAW", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_POOLKEYSRAW )}, NULL },
{ "HIX_POOLLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_POOLLOCK )}, NULL },
{ "HIX_POOLSET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_POOLSET )}, NULL },
{ "HIX_POOLSETRAW", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_POOLSETRAW )}, NULL },
{ "HIX_POOLSIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_POOLSIZE )}, NULL },
{ "HIX_POOLUNLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_POOLUNLOCK )}, NULL },
{ "HIX_PREAMBLELINES", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_PREAMBLELINES )}, NULL },
{ "HIX_PRGROUTE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_PRGROUTE )}, NULL },
{ "HIX_PROXYINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_PROXYINIT )}, NULL },
{ "HIX_RATELIMITESTIMATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_RATELIMITESTIMATE )}, NULL },
{ "HIX_REGEXESCAPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_REGEXESCAPE )}, NULL },
{ "HIX_RESOURCEHTML", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_RESOURCEHTML )}, NULL },
{ "HIX_RESPONSERAW", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_RESPONSERAW )}, NULL },
{ "HIX_RESPONSESTREAMSTART", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_RESPONSESTREAMSTART )}, NULL },
{ "HIX_ROUTEADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ROUTEADD )}, NULL },
{ "HIX_ROUTEDELETE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ROUTEDELETE )}, NULL },
{ "HIX_ROUTEDISPATCH", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ROUTEDISPATCH )}, NULL },
{ "HIX_ROUTEDISPREF", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ROUTEDISPREF )}, NULL },
{ "HIX_ROUTEDISPRESET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ROUTEDISPRESET )}, NULL },
{ "HIX_ROUTEGETACTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ROUTEGETACTION )}, NULL },
{ "HIX_ROUTEGROUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ROUTEGROUP )}, NULL },
{ "HIX_ROUTEHASACTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ROUTEHASACTION )}, NULL },
{ "HIX_ROUTELIST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ROUTELIST )}, NULL },
{ "HIX_ROUTEPARAM", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ROUTEPARAM )}, NULL },
{ "HIX_ROUTEREGISTERACTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ROUTEREGISTERACTION )}, NULL },
{ "HIX_ROUTESETHANDLER", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ROUTESETHANDLER )}, NULL },
{ "HIX_ROUTESISINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ROUTESISINIT )}, NULL },
{ "HIX_ROUTESLOAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ROUTESLOAD )}, NULL },
{ "HIX_ROUTESRESTORE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ROUTESRESTORE )}, NULL },
{ "HIX_ROUTESSNAPSHOT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ROUTESSNAPSHOT )}, NULL },
{ "HIX_SAFEDIRDELETE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SAFEDIRDELETE )}, NULL },
{ "HIX_SAFEERASE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SAFEERASE )}, NULL },
{ "HIX_SAFEPATHALLOWED", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SAFEPATHALLOWED )}, NULL },
{ "HIX_SAFEREGISTERDIR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SAFEREGISTERDIR )}, NULL },
{ "HIX_SAVECONFIG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SAVECONFIG )}, NULL },
{ "HIX_SERVERDORMANTHIXSTYLEFORTEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SERVERDORMANTHIXSTYLEFORTEST )}, NULL },
{ "HIX_SERVERISRUNNING", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SERVERISRUNNING )}, NULL },
{ "HIX_SERVERLIFECYCLEFORTEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SERVERLIFECYCLEFORTEST )}, NULL },
{ "HIX_SERVERMUTEXREADYFORTEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SERVERMUTEXREADYFORTEST )}, NULL },
{ "HIX_SERVERPROXIEDFORTEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SERVERPROXIEDFORTEST )}, NULL },
{ "HIX_SERVERREQUESTSTOP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SERVERREQUESTSTOP )}, NULL },
{ "HIX_SERVERREQUESTSTOPCLEARFORTEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SERVERREQUESTSTOPCLEARFORTEST )}, NULL },
{ "HIX_SERVERSETDORMANTHIXSTYLEFORTEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SERVERSETDORMANTHIXSTYLEFORTEST )}, NULL },
{ "HIX_SERVERSTOPREQUESTEDFORTEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SERVERSTOPREQUESTEDFORTEST )}, NULL },
{ "HIX_SESSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SESSION )}, NULL },
{ "HIX_SESSIONDESTROY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SESSIONDESTROY )}, NULL },
{ "HIX_SESSIONFILEGCFORTEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SESSIONFILEGCFORTEST )}, NULL },
{ "HIX_SESSIONFILELOADFORTEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SESSIONFILELOADFORTEST )}, NULL },
{ "HIX_SESSIONFILEWRITEFORTEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SESSIONFILEWRITEFORTEST )}, NULL },
{ "HIX_SESSIONGET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SESSIONGET )}, NULL },
{ "HIX_SESSIONMEMSETFORTEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SESSIONMEMSETFORTEST )}, NULL },
{ "HIX_SESSIONNEWID", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SESSIONNEWID )}, NULL },
{ "HIX_SESSIONROTATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SESSIONROTATE )}, NULL },
{ "HIX_SESSIONSAVE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SESSIONSAVE )}, NULL },
{ "HIX_SESSIONSET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SESSIONSET )}, NULL },
{ "HIX_SETCONFIG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SETCONFIG )}, NULL },
{ "HIX_SETCONTEXT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SETCONTEXT )}, NULL },
{ "HIX_SETCOOKIE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SETCOOKIE )}, NULL },
{ "HIX_SETERRORHANDLER", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SETERRORHANDLER )}, NULL },
{ "HIX_SETLIFECYCLEHOOK", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SETLIFECYCLEHOOK )}, NULL },
{ "HIX_SETMIME", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SETMIME )}, NULL },
{ "HIX_SETREQUEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SETREQUEST )}, NULL },
{ "HIX_SETSTATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SETSTATUS )}, NULL },
{ "HIX_SHOWERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SHOWERROR )}, NULL },
{ "HIX_SOCKETCONFIGURE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SOCKETCONFIGURE )}, NULL },
{ "HIX_SOCKETINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SOCKETINIT )}, NULL },
{ "HIX_SOCKETPEEK", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SOCKETPEEK )}, NULL },
{ "HIX_SOCKETPEEKSSL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SOCKETPEEKSSL )}, NULL },
{ "HIX_SSEBROADCAST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SSEBROADCAST )}, NULL },
{ "HIX_SSECOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SSECOUNT )}, NULL },
{ "HIX_SSESETUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SSESETUP )}, NULL },
{ "HIX_STATUSTEXT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_STATUSTEXT )}, NULL },
{ "HIX_SUBVERSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_SUBVERSION )}, NULL },
{ "HIX_THROW", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_THROW )}, NULL },
{ "HIX_TIMEOUTSEC", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_TIMEOUTSEC )}, NULL },
{ "HIX_TOKENCONSTANTEQ", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_TOKENCONSTANTEQ )}, NULL },
{ "HIX_TOKENGENRANDOM", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_TOKENGENRANDOM )}, NULL },
{ "HIX_TOKENGETSECRET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_TOKENGETSECRET )}, NULL },
{ "HIX_TOKENMAKE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_TOKENMAKE )}, NULL },
{ "HIX_TOKENSETSECRET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_TOKENSETSECRET )}, NULL },
{ "HIX_TOKENVALID", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_TOKENVALID )}, NULL },
{ "HIX_TRACEALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_TRACEALL )}, NULL },
{ "HIX_TRACEENABLED", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_TRACEENABLED )}, NULL },
{ "HIX_TRACEGETALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_TRACEGETALL )}, NULL },
{ "HIX_TRACESET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_TRACESET )}, NULL },
{ "HIX_TRANSPILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_TRANSPILE )}, NULL },
{ "HIX_URLDECODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_URLDECODE )}, NULL },
{ "HIX_USEREXIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_USEREXIT )}, NULL },
{ "HIX_USERINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_USERINIT )}, NULL },
{ "HIX_VALCAST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_VALCAST )}, NULL },
{ "HIX_VALCHECK", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_VALCHECK )}, NULL },
{ "HIX_VALIDCONFIG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_VALIDCONFIG )}, NULL },
{ "HIX_VALIDIP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_VALIDIP )}, NULL },
{ "HIX_VALSANITIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_VALSANITIZE )}, NULL },
{ "HIX_VERSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_VERSION )}, NULL },
{ "HIX_VIEWCACHECLEAR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_VIEWCACHECLEAR )}, NULL },
{ "HIX_VIEWCACHEINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_VIEWCACHEINIT )}, NULL },
{ "HIX_VIEW_PARAMS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_VIEW_PARAMS )}, NULL },
{ "HIX_VIEW_VIEWER", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_VIEW_VIEWER )}, NULL },
{ "HIX_WANTSJSON", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_WANTSJSON )}, NULL },
{ "HIX_WAPISTUBS_DUMMY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_WAPISTUBS_DUMMY )}, NULL },
{ "HIX_WORKERHTTP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_WORKERHTTP )}, NULL },
{ "HIX_WORKERPROTECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_WORKERPROTECT )}, NULL },
{ "HIX_WORKERREST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_WORKERREST )}, NULL },
{ "HIX_WORKERWS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_WORKERWS )}, NULL },
{ "HIX_WSBUILDFRAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_WSBUILDFRAME )}, NULL },
{ "HIX_WSGETCALLBACKS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_WSGETCALLBACKS )}, NULL },
{ "HIX_WSSAFEEVAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_WSSAFEEVAL )}, NULL },
{ "HIX_WSSETCALLBACKS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_WSSETCALLBACKS )}, NULL },
{ "HIX_WSTESTBUILDCLIENTFRAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_WSTESTBUILDCLIENTFRAME )}, NULL },
{ "HIX_WSTESTRUNFRAMELOOP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_WSTESTRUNFRAMELOOP )}, NULL },
{ "HIX_ZOMBIEADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ZOMBIEADD )}, NULL },
{ "HIX_ZOMBIECOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ZOMBIECOUNT )}, NULL },
{ "HIX_ZOMBIEDEAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ZOMBIEDEAD )}, NULL },
{ "HIX_ZOMBIEINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ZOMBIEINIT )}, NULL },
{ "HIX_ZOMBIEOVERLOAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ZOMBIEOVERLOAD )}, NULL },
{ "HIX_ZOMBIEPURGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ZOMBIEPURGE )}, NULL },
{ "HIX_ZOMBIEREPORT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HIX_ZOMBIEREPORT )}, NULL },
{ "LANGSTRINGS_EN", {HB_FS_PUBLIC}, {HB_FUNCNAME( LANGSTRINGS_EN )}, NULL },
{ "LANGSTRINGS_ES", {HB_FS_PUBLIC}, {HB_FUNCNAME( LANGSTRINGS_ES )}, NULL },
{ "MW_API_ADMIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( MW_API_ADMIN )}, NULL },
{ "MW_API_JWT", {HB_FS_PUBLIC}, {HB_FUNCNAME( MW_API_JWT )}, NULL },
{ "MW_WEB_ADMIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( MW_WEB_ADMIN )}, NULL },
{ "MW_WEB_AUTH", {HB_FS_PUBLIC}, {HB_FUNCNAME( MW_WEB_AUTH )}, NULL },
{ "MW_WEB_EDIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( MW_WEB_EDIT )}, NULL },
{ "MW_WEB_SESSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( MW_WEB_SESSION )}, NULL },
{ "SETHARUFONTDIR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETHARUFONTDIR )}, NULL },
{ "SHOWERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SHOWERROR )}, NULL },
{ "TFLASH", {HB_FS_PUBLIC}, {HB_FUNCNAME( TFLASH )}, NULL },
{ "THIXCONTEXT", {HB_FS_PUBLIC}, {HB_FUNCNAME( THIXCONTEXT )}, NULL },
{ "THIXDISPATCHER", {HB_FS_PUBLIC}, {HB_FUNCNAME( THIXDISPATCHER )}, NULL },
{ "THIXERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( THIXERROR )}, NULL },
{ "THIXIO", {HB_FS_PUBLIC}, {HB_FUNCNAME( THIXIO )}, NULL },
{ "THIXLOGGER", {HB_FS_PUBLIC}, {HB_FUNCNAME( THIXLOGGER )}, NULL },
{ "THIXMETRICS", {HB_FS_PUBLIC}, {HB_FUNCNAME( THIXMETRICS )}, NULL },
{ "THIXPOOL", {HB_FS_PUBLIC}, {HB_FUNCNAME( THIXPOOL )}, NULL },
{ "THIXREQUEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( THIXREQUEST )}, NULL },
{ "THIXSERVER", {HB_FS_PUBLIC}, {HB_FUNCNAME( THIXSERVER )}, NULL },
{ "THIXSESSIONPROXY", {HB_FS_PUBLIC}, {HB_FUNCNAME( THIXSESSIONPROXY )}, NULL },
{ "THIXSOCKET", {HB_FS_PUBLIC}, {HB_FUNCNAME( THIXSOCKET )}, NULL },
{ "THIXSSECONN", {HB_FS_PUBLIC}, {HB_FUNCNAME( THIXSSECONN )}, NULL },
{ "THIXVALIDATOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( THIXVALIDATOR )}, NULL },
{ "THIXWSCONN", {HB_FS_PUBLIC}, {HB_FUNCNAME( THIXWSCONN )}, NULL },
{ "TPDF", {HB_FS_PUBLIC}, {HB_FUNCNAME( TPDF )}, NULL },
{ "UAUTHLOGOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( UAUTHLOGOUT )}, NULL },
{ "UAUTHUSER", {HB_FS_PUBLIC}, {HB_FUNCNAME( UAUTHUSER )}, NULL },
{ "UBASEMIDDLEWARE", {HB_FS_PUBLIC}, {HB_FUNCNAME( UBASEMIDDLEWARE )}, NULL },
{ "UBODY", {HB_FS_PUBLIC}, {HB_FUNCNAME( UBODY )}, NULL },
{ "UCONFIG", {HB_FS_PUBLIC}, {HB_FUNCNAME( UCONFIG )}, NULL },
{ "UCONTENTLENGTH", {HB_FS_PUBLIC}, {HB_FUNCNAME( UCONTENTLENGTH )}, NULL },
{ "UCONTENTTYPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( UCONTENTTYPE )}, NULL },
{ "UCONTEXT", {HB_FS_PUBLIC}, {HB_FUNCNAME( UCONTEXT )}, NULL },
{ "UCOOKIE", {HB_FS_PUBLIC}, {HB_FUNCNAME( UCOOKIE )}, NULL },
{ "UCSRFTOHTML", {HB_FS_PUBLIC}, {HB_FUNCNAME( UCSRFTOHTML )}, NULL },
{ "UCURL", {HB_FS_PUBLIC}, {HB_FUNCNAME( UCURL )}, NULL },
{ "UCURRENTUSER", {HB_FS_PUBLIC}, {HB_FUNCNAME( UCURRENTUSER )}, NULL },
{ "UDATETOHTML", {HB_FS_PUBLIC}, {HB_FUNCNAME( UDATETOHTML )}, NULL },
{ "UDBF", {HB_FS_PUBLIC}, {HB_FUNCNAME( UDBF )}, NULL },
{ "UECHO", {HB_FS_PUBLIC}, {HB_FUNCNAME( UECHO )}, NULL },
{ "UENV", {HB_FS_PUBLIC}, {HB_FUNCNAME( UENV )}, NULL },
{ "UERRORPAGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( UERRORPAGE )}, NULL },
{ "UFILES", {HB_FS_PUBLIC}, {HB_FUNCNAME( UFILES )}, NULL },
{ "UFLASH", {HB_FS_PUBLIC}, {HB_FUNCNAME( UFLASH )}, NULL },
{ "UFLUSH", {HB_FS_PUBLIC}, {HB_FUNCNAME( UFLUSH )}, NULL },
{ "UGET", {HB_FS_PUBLIC}, {HB_FUNCNAME( UGET )}, NULL },
{ "UGETCONFIG", {HB_FS_PUBLIC}, {HB_FUNCNAME( UGETCONFIG )}, NULL },
{ "UGETMIME", {HB_FS_PUBLIC}, {HB_FUNCNAME( UGETMIME )}, NULL },
{ "UGETPPRULES", {HB_FS_PUBLIC}, {HB_FUNCNAME( UGETPPRULES )}, NULL },
{ "UGETRESOURCE", {HB_FS_PUBLIC}, {HB_FUNCNAME( UGETRESOURCE )}, NULL },
{ "UGETROLES", {HB_FS_PUBLIC}, {HB_FUNCNAME( UGETROLES )}, NULL },
{ "UHASHTOHTMLSELECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( UHASHTOHTMLSELECT )}, NULL },
{ "UHASROLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( UHASROLE )}, NULL },
{ "UHASSCOPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( UHASSCOPE )}, NULL },
{ "UHEADER", {HB_FS_PUBLIC}, {HB_FUNCNAME( UHEADER )}, NULL },
{ "UHOST", {HB_FS_PUBLIC}, {HB_FUNCNAME( UHOST )}, NULL },
{ "UHTMLENCODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( UHTMLENCODE )}, NULL },
{ "UIP", {HB_FS_PUBLIC}, {HB_FUNCNAME( UIP )}, NULL },
{ "UISAJAX", {HB_FS_PUBLIC}, {HB_FUNCNAME( UISAJAX )}, NULL },
{ "UISDEV", {HB_FS_PUBLIC}, {HB_FUNCNAME( UISDEV )}, NULL },
{ "UISFORM", {HB_FS_PUBLIC}, {HB_FUNCNAME( UISFORM )}, NULL },
{ "UISGET", {HB_FS_PUBLIC}, {HB_FUNCNAME( UISGET )}, NULL },
{ "UISHTTPS", {HB_FS_PUBLIC}, {HB_FUNCNAME( UISHTTPS )}, NULL },
{ "UISINTEGER", {HB_FS_PUBLIC}, {HB_FUNCNAME( UISINTEGER )}, NULL },
{ "UISIP", {HB_FS_PUBLIC}, {HB_FUNCNAME( UISIP )}, NULL },
{ "UISJSON", {HB_FS_PUBLIC}, {HB_FUNCNAME( UISJSON )}, NULL },
{ "UISMAIL", {HB_FS_PUBLIC}, {HB_FUNCNAME( UISMAIL )}, NULL },
{ "UISMULTIPART", {HB_FS_PUBLIC}, {HB_FUNCNAME( UISMULTIPART )}, NULL },
{ "UISNUMERIC", {HB_FS_PUBLIC}, {HB_FUNCNAME( UISNUMERIC )}, NULL },
{ "UISPOST", {HB_FS_PUBLIC}, {HB_FUNCNAME( UISPOST )}, NULL },
{ "UISPROD", {HB_FS_PUBLIC}, {HB_FUNCNAME( UISPROD )}, NULL },
{ "UISURL", {HB_FS_PUBLIC}, {HB_FUNCNAME( UISURL )}, NULL },
{ "UJSON", {HB_FS_PUBLIC}, {HB_FUNCNAME( UJSON )}, NULL },
{ "UJWT", {HB_FS_PUBLIC}, {HB_FUNCNAME( UJWT )}, NULL },
{ "ULOGICTOHTMLCHECKED", {HB_FS_PUBLIC}, {HB_FUNCNAME( ULOGICTOHTMLCHECKED )}, NULL },
{ "UMETHOD", {HB_FS_PUBLIC}, {HB_FUNCNAME( UMETHOD )}, NULL },
{ "UMIDDLEWARE", {HB_FS_PUBLIC}, {HB_FUNCNAME( UMIDDLEWARE )}, NULL },
{ "UMWCONFIG", {HB_FS_PUBLIC}, {HB_FUNCNAME( UMWCONFIG )}, NULL },
{ "UNOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( UNOW )}, NULL },
{ "UOSFILENAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( UOSFILENAME )}, NULL },
{ "UPARAM", {HB_FS_PUBLIC}, {HB_FUNCNAME( UPARAM )}, NULL },
{ "UPATH", {HB_FS_PUBLIC}, {HB_FUNCNAME( UPATH )}, NULL },
{ "UPEERALIVE", {HB_FS_PUBLIC}, {HB_FUNCNAME( UPEERALIVE )}, NULL },
{ "UPORT", {HB_FS_PUBLIC}, {HB_FUNCNAME( UPORT )}, NULL },
{ "UPOST", {HB_FS_PUBLIC}, {HB_FUNCNAME( UPOST )}, NULL },
{ "UPROD", {HB_FS_PUBLIC}, {HB_FUNCNAME( UPROD )}, NULL },
{ "UQUERY", {HB_FS_PUBLIC}, {HB_FUNCNAME( UQUERY )}, NULL },
{ "UREDIRECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( UREDIRECT )}, NULL },
{ "UREQUEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( UREQUEST )}, NULL },
{ "URESOURCETOHTML", {HB_FS_PUBLIC}, {HB_FUNCNAME( URESOURCETOHTML )}, NULL },
{ "UROOT", {HB_FS_PUBLIC}, {HB_FUNCNAME( UROOT )}, NULL },
{ "UROOTPATH", {HB_FS_PUBLIC}, {HB_FUNCNAME( UROOTPATH )}, NULL },
{ "UROUTE", {HB_FS_PUBLIC}, {HB_FUNCNAME( UROUTE )}, NULL },
{ "USCHEME", {HB_FS_PUBLIC}, {HB_FUNCNAME( USCHEME )}, NULL },
{ "USEND", {HB_FS_PUBLIC}, {HB_FUNCNAME( USEND )}, NULL },
{ "USENDCHUNK", {HB_FS_PUBLIC}, {HB_FUNCNAME( USENDCHUNK )}, NULL },
{ "USENDEMPTY", {HB_FS_PUBLIC}, {HB_FUNCNAME( USENDEMPTY )}, NULL },
{ "USENDERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( USENDERROR )}, NULL },
{ "USENDHTML", {HB_FS_PUBLIC}, {HB_FUNCNAME( USENDHTML )}, NULL },
{ "USENDJSON", {HB_FS_PUBLIC}, {HB_FUNCNAME( USENDJSON )}, NULL },
{ "USENDSTREAMEND", {HB_FS_PUBLIC}, {HB_FUNCNAME( USENDSTREAMEND )}, NULL },
{ "USENDSTREAMSTART", {HB_FS_PUBLIC}, {HB_FUNCNAME( USENDSTREAMSTART )}, NULL },
{ "USENDTEXT", {HB_FS_PUBLIC}, {HB_FUNCNAME( USENDTEXT )}, NULL },
{ "USENDVIEW", {HB_FS_PUBLIC}, {HB_FUNCNAME( USENDVIEW )}, NULL },
{ "USESSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( USESSION )}, NULL },
{ "USESSIONROTATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( USESSIONROTATE )}, NULL },
{ "USETCOOKIE", {HB_FS_PUBLIC}, {HB_FUNCNAME( USETCOOKIE )}, NULL },
{ "USETHEADER", {HB_FS_PUBLIC}, {HB_FUNCNAME( USETHEADER )}, NULL },
{ "USETMIME", {HB_FS_PUBLIC}, {HB_FUNCNAME( USETMIME )}, NULL },
{ "USETSTATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( USETSTATUS )}, NULL },
{ "USTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( USTR )}, NULL },
{ "UVALIDATEGET", {HB_FS_PUBLIC}, {HB_FUNCNAME( UVALIDATEGET )}, NULL },
{ "UVALIDATEJSON", {HB_FS_PUBLIC}, {HB_FUNCNAME( UVALIDATEJSON )}, NULL },
{ "UVALIDATEORFAIL", {HB_FS_PUBLIC}, {HB_FUNCNAME( UVALIDATEORFAIL )}, NULL },
{ "UVALIDATEPARAMS", {HB_FS_PUBLIC}, {HB_FUNCNAME( UVALIDATEPARAMS )}, NULL },
{ "UVALIDATEPOST", {HB_FS_PUBLIC}, {HB_FUNCNAME( UVALIDATEPOST )}, NULL },
{ "UVALIDATOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( UVALIDATOR )}, NULL },
{ "UVALIDATORONE", {HB_FS_PUBLIC}, {HB_FUNCNAME( UVALIDATORONE )}, NULL },
{ "UVIEW", {HB_FS_PUBLIC}, {HB_FUNCNAME( UVIEW )}, NULL },
{ "UVIEW_CSS", {HB_FS_PUBLIC}, {HB_FUNCNAME( UVIEW_CSS )}, NULL },
{ "UVIEW_EXEC", {HB_FS_PUBLIC}, {HB_FUNCNAME( UVIEW_EXEC )}, NULL },
{ "UVIEW_JS", {HB_FS_PUBLIC}, {HB_FUNCNAME( UVIEW_JS )}, NULL },
{ "UWANTSJSON", {HB_FS_PUBLIC}, {HB_FUNCNAME( UWANTSJSON )}, NULL },
{ "UWRITE", {HB_FS_PUBLIC}, {HB_FUNCNAME( UWRITE )}, NULL },
{ "WAPI_OUTPUTDEBUGSTRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( WAPI_OUTPUTDEBUGSTRING )}, NULL },
{ "WAPI_SHELLEXECUTE", {HB_FS_PUBLIC}, {HB_FUNCNAME( WAPI_SHELLEXECUTE )}, NULL },
{ "_", {HB_FS_PUBLIC}, {HB_FUNCNAME( _ )}, NULL },
{ "_C", {HB_FS_PUBLIC}, {HB_FUNCNAME( _C )}, NULL },
{ "_D", {HB_FS_PUBLIC}, {HB_FUNCNAME( _D )}, NULL },
{ "_HIXLPWAIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( _HIXLPWAIT )}, NULL },
{ "_HIXROUTESETSOURCE", {HB_FS_PUBLIC}, {HB_FUNCNAME( _HIXROUTESETSOURCE )}, NULL },
{ "_HIXSSEREGISTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( _HIXSSEREGISTER )}, NULL },
{ "_HIXSSEUNREGISTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( _HIXSSEUNREGISTER )}, NULL },
{ "_L", {HB_FS_PUBLIC}, {HB_FUNCNAME( _L )}, NULL },
{ "_STACK", {HB_FS_PUBLIC}, {HB_FUNCNAME( _STACK )}, NULL },
{ "_T", {HB_FS_PUBLIC}, {HB_FUNCNAME( _T )}, NULL },
{ "_W", {HB_FS_PUBLIC}, {HB_FUNCNAME( _W )}, NULL },
{ "__HBEXTERN__HIX_SERVER__", {HB_FS_PUBLIC | HB_FS_FIRST | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__HIX_SERVER__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_HIX_SERVER, "/home/jack/Projects/hix/hix_server.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_HIX_SERVER
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_HIX_SERVER )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__HIX_SERVER__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

